---
info:
  component: Default Single Swagger Document Server for MicroService

server:
  port: 8014

documentation: 
  baseurl: http://localhost
  swagger: 
    services:   
      - 
        name: message
        url: ${documentation.baseurl}:8001/v2/api-docs
        version: 2.0
      - 
        name: user
        url: ${documentation.baseurl}:8002/v2/api-docs
        version: 2.0

 
    